[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info

[program:transit]
command=uvicorn transit.main:app --host 127.0.0.1 --port 8000
directory=/app
autostart=true
autorestart=true
startsecs=3
stderr_logfile=/var/log/supervisor/transit.err.log
stdout_logfile=/var/log/supervisor/transit.out.log
environment=PYTHONUNBUFFERED="1"

[program:caddy]
command=caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
autostart=true
autorestart=true
startsecs=3
stderr_logfile=/var/log/supervisor/caddy.err.log
stdout_logfile=/var/log/supervisor/caddy.out.log
